### ISSUE TITLE
Can you provide code for Code of model training？

### ISSUE THREAD

**Issue by wz429** [LinZhuoChen/SGNet#1]
Hello! Do you have the source code for model training? 
Is it convenient to share it? I am doing an experiment and need to modify the task of the model and retrain it.

**Comment by LinZhuoChen** [comment]
Hello，Thank you for your attention. I can share it by email, please give me your email address.

**Comment by wz429** [comment]
> Hello，Thank you for your attention. I can share it by email, please give me your email address.

imzhwang@163.com，Thank you.

**Comment by ArthurZucker** [comment]
Hello, could you also share it with me? Also working on the code and I wanna train it. 
my email address : arthur.zucker@gmail.com

**Comment by foreverfei** [comment]
Could you also share the training code with me? Thanks! my email address:foreverfei875@gmail.com

**Comment by sanersbug** [comment]
Could you also share the training code with me? Thank you very very very much! my email address: cswei1874@gmail.com

**Comment by changshuowang** [comment]
Hello, could you also share the training code with me? Thank you very very very much! my email address: wangchangshuo@semi.ac.cn

**Comment by amyzxq** [comment]
Hello, could you also share the training code with me? Thank you very  much! my email address:38853612@qq.com

**Comment by ArthurZucker** [comment]
I think no one ever got any answer here! 😅

**Comment by wuYwen1** [comment]
Could you also share the training code with me? Thanks! my email address:hhu_wyw@163.com
